services:
  web:
    image: php:7.4.28-fpm-alpine3.14
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_web
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/var/www/html # mount local "app" folder to container
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "8080:80"
    networks:
      - webnet
    extra_hosts:
      - "host.docker.internal:host-gateway" # Needed for Xdebug
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      API_KEY: ABCD1234
      DB_HOST: db
      DB_NAME: native_api
      DB_USER: user
      DB_PASSWORD: user

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: native_api
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33060:3306" # port 3306 already in use on my local environment
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "8082:80"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    ports:
      - "8081:80"
    networks:
      - webnet

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  db_data: